### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [paudirac/Error-ROP#3]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=Error-ROP%200.02

Sample fail report:

http://www.cpantesters.org/cpan/report/dfb07864-7cc8-11e7-913a-e8a8792a4f99

Diagnostics:

syntax error at t/Example.t line 5, near "package MooseSut {
  "
Execution of t/Example.t aborted due to compilation errors.

If this is intentional, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH&&Thanks,

**Comment by paudirac** [comment]
Thanks. I just declared the perl version.
